name: 'proto-c compile'
description: 'compile proto-c prototypes'
inputs: 
  files:
    description: 'file name pattern'
    required: true
  output-dir:
    description: 'output directory for prototypes'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'docker://tellsoftware/protobuf-c-compile-action:v0'
  env:
    files=${{ inputs.files }}: ''
    output_dir=${{ inputs.output_dir }}: ''

